# Generated by Django 4.1.7 on 2023-05-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cardholder_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='result',
        ),
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_number',
            field=models.CharField(default='', max_length=16, verbose_name='Card Number'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.CharField(default='', max_length=100, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cvv',
            field=models.CharField(default='', max_length=4, verbose_name='CVV'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exp_date',
            field=models.CharField(default='', max_length=5, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.CharField(default='', max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='', max_length=100, verbose_name='Transaction Type'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='zip_code',
            field=models.CharField(default='', max_length=10, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(default='', max_length=100),
        ),
    ]
